/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'care' at '11/4/16 1:00 PM' with Gradle 2.14.1
 *
 * @author care, @date 11/4/16 1:00 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
